### ISSUE TITLE
Create customization module for types of assay templates supported

### ISSUE THREAD

**Issue by kelshmo** [Sage-Bionetworks/dccvalidator#107]
The templates supported for PEC and AMPAD will differ, @karawoo could you provide your design feedback on which customization option is preferred: 

1. Keep existing format, update synID and [vector of allowable assay types](https://github.com/Sage-Bionetworks/dccvalidator/blob/master/R/check-col-names.R#L107)
2. Follow the syntax proposed [here](https://github.com/Sage-Bionetworks/dccvalidator/pull/93#issuecomment-541847366) to create custom modules.

**Comment by karawoo** [comment]
I think this should go into the underlying functions, i.e. option 1. That way if you wanted to validate in a non-app context (such as a custom script), you could do the same checks that the app does.

However I don't want to do complicated conditionals to find the templates based on both their name and consortium. Perhaps instead of taking the names as arguments, these functions should take the synID of the template, and when we call them in the app we would provide the appropriate synIDs.

Note that the `check_cols_assay()/biospecimen()` etc. functions are all wrappers around `check_col_names()`, which is already flexible enough to handle any template, provided you have already downloaded it:

https://github.com/Sage-Bionetworks/dccvalidator/blob/6c4297d6cf1bc78e07ce4d16c784dbc14df80265/R/check-col-names.R#L13-L24

**Comment by kelshmo** [comment]
Moving forward with option 1.
