### ISSUE TITLE
Consider pulling study name from manifest or validating study against manifest

### ISSUE THREAD

**Issue by karawoo** [Sage-Bionetworks/dccvalidator#134]
Rather than having user enter it into app

**Comment by karawoo** [comment]
I think that we should consider closing this as `wontfix`. I'm not sure how we would do this since users can use the validator to check metadata files without including a manifest.

**Comment by Aryllen** [comment]
That's a good point. This definitely wouldn't work if it were solely to get the study name for annotations and looking up existing study information (when we get to that point).

We could get the study name from the manifest and compare it to the one they entered into the app (referring to second half of the issue title). This _might_ have some benefit. One downside is that the person could have it correctly in the manifest, but had a typo in the name they gave the app (assuming they typed it in as a new study name). I think this would require both values to show in the details so they could see what the mistake was.

**Comment by Aryllen** [comment]
Going back to Kara's idea of closing this as wontfix since I'm not sure there is enough (or any) benefit to checking that the name entered in the app is the same name as the name in the manifest. I could see this being useful if it affect the files uploaded via the app since, if they entered the wrong name in the app, the files would appear in the wrong study for dccmonitor. However, there's lots of ways this could go wrong.
