### ISSUE TITLE
Local deployment with config file

### ISSUE THREAD

**Issue by kelshmo** [Sage-Bionetworks/dccvalidator#145]
When we write instructions on customizing the config file, note that during local deployment `Sys.unsetenv("R_CONFIG_ACTIVE")` is required. Changing the value in the `app.R` file and saving the file is not sufficient.

**Comment by karawoo** [comment]
I think so far you, @Aryllen, and I have all gotten bitten by conditional setting of the environment variable. @kdaily I know you wanted this option so that you could set the config outside of the app.R file, but the problem is that once the app is cloned on the shiny server it's running these lines right away: 
https://github.com/Sage-Bionetworks/dccvalidator/blob/db46666717697f1292629265dcabe0d5c2e43300/app.R#L5-L7

and then customizing the environment variable in app.R has no effect. So either we should remove it from the app altogether and only set the environment variable separately, or we should remove the conditional.

**Comment by kdaily** [comment]
Oops. That's not a useful side effect! Would defer to you whatever is most appropriate of those choices! Only allowing setting it in the environment means having to do console stuff, so I can see how that isn't as desirable.

**Comment by karawoo** [comment]
I feel like writing it in the config file makes most sense as it is easiest to determine which configuration the app is running with. I would propose removing the conditional and leaving `Sys.setenv(R_CONFIG_ACTIVE = "default")` in app.R. Then when someone is deploying the app they either change this line to their config, or remove it altogether if they want to set the environment variable some other way. Sound ok?

**Comment by kdaily** [comment]
:+1: thanks @karawoo!
