### ISSUE TITLE
Integer columns read in as doubles

### ISSUE THREAD

**Issue by karawoo** [Sage-Bionetworks/dccvalidator#300]
readr reads in all numeric columns as doubles, which breaks values that should be integer: 

``` r
library("dccvalidator")
#> Loading required package: shinyBS
library("readr")

synapse <- reticulate::import("synapseclient")
syn <- synapse$Synapse()
syn$login()

annots <- get_synapse_annotations("syn21459391", syn = syn)
file <- "bindingDensity\n5"
dat <- read_csv(file)
dat
#> # A tibble: 1 x 1
#>   bindingDensity
#>            <dbl>
#> 1              5

check_annotation_values(dat, annotations = annots)
#> <error/check_fail>
#> Some annotation values are invalid
```

<sup>Created on 2020-02-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

Also related to #284 as they both deal with how readr treats columns. We could fix it there, or another opton would be to add numeric -> integer to `can_coerce()` if all the numeric values are whole numbers.

**Comment by Aryllen** [comment]
I think adding another option to `can_coerce()` would be the way to go. Trying to fix every column after reading the file in would take some time and be unnecessary in many cases.

**Comment by karawoo** [comment]
> Trying to fix every column after reading the file in would take some time and be unnecessary in many cases.

Agreed. I think we should also keep tabs on these issues though, since it's come up twice now recently that valid data gets read in in a way that makes it seem invalid.

**Comment by Aryllen** [comment]
Also agreed. I feel like it comes down to using a base package versus readr (or a different package that works similarly). 

On the one hand, we have to specify things like `stringsAsFactors = FALSE` and potentially `check.names = FALSE`, and could still have type issues due to guessing types across too many columns. 

On the other hand, we don't have to specify anything other than reading in everything as strings, but then have to have a fancy function to check if the type can be coerced to one that is accepted. I've also found a few challenges with readr's `spec_tbl` type, which is a bit annoying. 

Not sure which is the better way to ultimately solve the problem in the long run.

**Comment by karawoo** [comment]
Yeah, we switched to readr in the first place for more stable column names in #262 so it seems like there are some tradeoffs here we'll have to decide between.
