### ISSUE TITLE
Weird characters in pkgdown site

### ISSUE THREAD

**Issue by karawoo** [Sage-Bionetworks/dccvalidator#338]
Our apostrophes are getting converted to something weird:
<img width="863" alt="Screen Shot 2020-04-03 at 4 35 24 PM" src="https://user-images.githubusercontent.com/4452678/78412723-3e296d00-75c9-11ea-9509-897b6c0156e0.png">

This appears in multiple locations in the pkgdown site.

**Comment by Aryllen** [comment]
Ugh, that's annoying. The old way of deploying built in a Linux environment, but this one is building in Mac. I'm not sure if that's the problem, though.

**Comment by Aryllen** [comment]
I looked into this a smidge and am still not sure how to fix, yet. It's only on the home page, which comes from the Readme, not our pre-rendered information. So it _should_ be directly related to how the site is being rendered in the GH Action environment. 

I know there has been some issues with the latest Mac update, but it still seems like grasping at straws. I could look into changing the Mac version or to a Linux build, though.

Another idea would be to try pulling the latest dev version of pkgdown and seeing if it is magically fixed. However, all the issues in the repo that are even mildy related have fixes that are in the latest CRAN version so that is also a stretch.

**Comment by karawoo** [comment]
I looked into this some more and it looks like it was due to a bug in the xml2 package that has since been fixed and released to CRAN. So I think it should be automatically fixed as long as future builds use the latest xml2 version.

**Comment by Aryllen** [comment]
Ooh, that would be great if it will fix itself on the next PR merge.

**Comment by karawoo** [comment]
Looks like all is back to normal after merging #342!
