### ISSUE TITLE
Consider splitting out app from package

### ISSUE THREAD

**Issue by karawoo** [Sage-Bionetworks/dccvalidator#426]
I'm opening this issue to discuss the possibility of splitting out the dccvalidator app from the package. The server and UI functions would continue to be provided by the package, but the app that we deploy would use them by calling `library("dccvalidator")` followed by `run_app()`. When I first started dccvalidator it actually was set up this way, and we combined the repos at some point because there was confusion about what functionality lived where. 

However, the combined repo has caused different confusion about what files are accessible and how: do we rely on the file/folder hierarchy of the repo (which is not portable to users who install the package), or rely on the installed versions of files in `inst/`? This in turn causes confusion about which changes are taking effect: changes to the code in `R/` take effect automatically when we deploy an updated version of the app, but changes to files in `inst/` do not because they are controlled by the version of dccvalidator captured in the renv lockfile. We also are unable to upgrade to the latest renv version, because it has a feature that prevents the current project from being snapshotted within the lockfile.

My feeling is that it would be more "correct" to split up the package (`dccvalidator`) and the app (`dccvalidator-app`). The app repo would have an renv lockfile, an app.R file that loads dccvalidator and runs the app, and a config file. We would remove renv, the config file, and the app.R file from this repo (but possibly provide a helper function to generate the skeleton of a config file). One downside I can see is that it would become a little more work to get updates from the package to the app. Currently we can usually merge a PR to dccvalidator, pull the changes onto the server, and have them take effect. Under the proposed setup we'd need to merge the PR to dccvalidator, update the dccvalidator version in `dccvalidator-app`'s lockfile, and pull _that_ change onto the shiny server.

@Aryllen @kelshmo would love to hear your thoughts

**Comment by Aryllen** [comment]
I've let this 'stew' a bit in the back of my mind. Overall, I've thought to use dccvalidator for other purposes than just the app, but it feels odd to install a package that feels mostly like an app. I have also been stalled by the fact that dccvalidator uses reticulate (purely because of the app), but most of what I am doing is easily done in synapser, which is incompatible.

Moving the app out of dccvalidator 'solves' one of those problems, but I would lean towards being heavy handed. Anything app-related could go in dccvalidator-app, including the server and ui functions. Everything related to the validation itself could stay in dccvalidator. Only separating out a handful of app-related bits to a different package seems less useful. For example, if someone wants to just have validation functions, they could use dccvalidator, but if they want to borrow a module for an app they are building (that might have nothing to do with validation), they could use dccvalidator-app.

If we had a scaled down dccvalidator, it might also be useful (at least to me) and more feasible/less work to have a synapser version on a different branch (or in some other fashion).

I would be happy to chat about this topic.

**Comment by Aryllen** [comment]
> I'm less excited about having dccvalidator's actual functionality split into two separate packages, because that won't solve the problems in my second paragraph -- the server/UI functions are some of the ones that use installed files in inst/ so if we move those to a different package that we continue to deploy by cloning the repo, we have all the same problems but now the code is split across two places, bringing us back to the issue that led us to merge the repos in the first place. 

Ah, that's a good point. It doesn't help if it doesn't fix the problem. Perhaps I am misunderstanding your second paragraph.

> This in turn causes confusion about which changes are taking effect: changes to the code in R/ take effect automatically when we deploy an updated version of the app, but changes to files in inst/ do not because they are controlled by the version of dccvalidator captured in the renv lockfile.

The new change to the inst/ files for removing the progress bars did not require a change to the version of dccvalidator in the lockfile. I only pulled the latest version of master and restarted the app with no problems. When running locally, I did use `devtools::install()`, as suggested, so I can't speak to whether it would have been a problem if I hadn't. 

> My thinking here was to separate the software we're developing from the deployment of that software.

Ah, I am thinking more in terms of separating out general purpose tools from targeted software applications.

> ...is there something that prevents you from using the non-app functions in dccvalidator even though the app is there too?

No, not really. It's just the mindset of what dccvalidator invokes when I think about it. It's not really a 'problem' with the package, but rather me. 😆

**Comment by karawoo** [comment]
Closing this as we've decided not to pursue it.
