### ISSUE TITLE
pkgdown failure fix

### ISSUE THREAD

**Issue by kelshmo** [Sage-Bionetworks/dccvalidator#437]
I noticed your `pkgdown` was also failing, [specifying](https://github.com/Sage-Bionetworks/sageseqr/commit/9a4e821c7d9a9ff381fb87ac9a5b7b9143ea7a87) `type = binary` fixed the problem for me.

**Comment by Aryllen** [comment]
Thank you! I haven't had time to check into it. I appreciate the help.

**Comment by Aryllen** [comment]
@karawoo, I haven't fiddled with the pkgdown stuff much. Is there a reason why we are [installing the dev version](https://github.com/Sage-Bionetworks/dccvalidator/blob/d0b7f63a518d89f4da248e662878293accdac7b2/.github/workflows/pkgdown.yaml#L34) in the GH Action? If we do not need the dev version, we could use @kelshmo's suggestion.

**Comment by karawoo** [comment]
I don't think so. According to the [original PR](https://github.com/Sage-Bionetworks/dccvalidator/pull/335) it looks like we copied it from the r-lib examples, which have since been updated to install the binary. I'm fine with making the change. 

FYI the pkgdown failure was due it one of its dependencies, textshaping, having issues being installed from source because system dependencies (harfbuzz and fribidi) are not installed. There are binaries of textshaping available now, so if we re-run the pkgdown workflow as-is I expect it would work. But I think installing the binary version going forward is probably a good change regardless.

**Comment by Aryllen** [comment]
> I'm fine with making the change.

Sounds good! 

> FYI the pkgdown failure was due it one of its dependencies, textshaping, having issues being installed from source because system dependencies (harfbuzz and fribidi) are not installed. There are binaries of textshaping available now, so if we re-run the pkgdown workflow as-is I expect it would work. But I think installing the binary version going forward is probably a good change regardless.

And yeah, I mostly just want to get rid of this issue altogether. I don't think this is the first time pkgdown has failed on us due to a dependency not having a binary, yet.
